Update skyportwings

diff --git a/skyportwings b/skyportwings
--- a/skyportwings
+++ b/skyportwings
@@ -1,20 +1,49 @@
 #!/bin/bash
 
-# Update package list and install dependencies
-sudo apt update
-sudo apt install -y curl software-properties-common
-curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
-sudo apt-get install nodejs -y 
-sudo apt install git -y
+# Para ASCII Art and Header
+echo -e "\n\033[1;36m"
+cat << "EOF"
 
-# Wings
+  
+  _____        _____            
+ |  __ \ /\   |  __ \     /\    
+ | |__) /  \  | |__) |   /  \   
+ |  ___/ /\ \ |  _  /   / /\ \  
+ | |  / ____ \| | \ \  / ____ \ 
+ |_| /_/    \_\_|  \_\/_/    \_\
+                                
+                                
 
-git clone https://github.com/achul123/skyportd.git
-cd skyportd 
-npm install
+ 🤍 Skyport Wings Installer - github.com/ParaNoob123
 
-echo_message "* cd skyportd"
+EOF
+echo -e "\033[0m"
 
-echo_message "* paste your configure code"
+echo -e "\033[1;34mStarting Installation of Skyport Wings \033[0m"
+echo "-------------------------------------"
 
-echo_message "* pm2 start ."
+# Installation Steps
+commands=(
+  "git clone https://github.com/achul123/skyportd.git"
+  "cd skyportd"
+  "npm install"
+  "cd skyportd"
+)
+
+# Execute commands with progress
+for i in "${!commands[@]}"; do
+  echo -e "\033[1;33m[$((i+1))/14] Executing:\033[0m \033[0;35m${commands[$i]}\033[0m"
+  eval "${commands[$i]}"
+  if [ $? -ne 0 ]; then
+    echo -e "\033[1;31mError occurred at step $((i+1)). Aborting installation.\033[0m"
+    exit 1
+  fi
+done
+
+# Completion Message
+echo -e "\n\033[1;32m-------------------------------------\033[0m"
+echo -e "\033[1;34m Then Paste Your Configure Of Node Then Do node .\033[0m"
+echo -e "\033[1;32m Skyport Wings installed successfully! 🎉\033[0m"
+echo -e "\033[1;35m           Made by Para\033[0m"
+echo -e "\033[1;35m       github.com/Para\033[0m"
+echo -e "\033[1;32m-------------------------------------\033[0m"
